### ISSUE TITLE
Q for const.py

### ISSUE THREAD

**Issue by Jiadosi** [SoftSec-KAIST/IMF#2]
hi!
I have a question for the Header in const.py
what does the function below working for?
`void log_CFTypeRef(FILE *f,CFTypeRef target)`
will it play a role in the following log-filtering part?
i tried to delete it and generated some logs, but got stuck in the ./filter-log step. I have no idea how to fix it.
looking for your reply.

**Comment by DaramG** [comment]
`log_CFTypeRef` function is required for logging `CFTypeRef` type in `hook.c` which is generated by `gen-hook`.
If you delete definition of `log_CFTypeRef` in `const.py`, `hook.c` could not be compiled.
So, if you got some logs without `log_CFTypeRef`, then those logs might be invalid.
And you got stuck in the `filter-log` step because you fed invalid logs to `filter-log`.

**Comment by Jiadosi** [comment]
I see. Thanks.
Now I am running an example with IMF on 2048 Game, just like you did in your paper.
I tried to write a python script in order to automatically open 2048 Game and generate random keyboard events. But failed to hook it.
So I try to open 2048 Game directly, still failed.
`DYLD_INSERT_LIBRARIES=./hook /Applications/2048\ Game.app/Contents/MacOS/2048\ Game`
2048 Game works well when I simply type the command 
`/Applications/2048\ Game.app/Contents/MacOS/2048\ Game`
Can you give me some hint? Or how did you run this example?
Thanks a looooot!

**Comment by DaramG** [comment]
You should check the sandbox of hooked application for writing API logs.
